### ISSUE TITLE
Have you looked into Wikidata and administrative divisions by country

### ISSUE THREAD

**Issue by salgo60** [sociepy/covid19-vaccination-subnational#1]
Excellent 

Shouldnt we try to use **same as** instead of just text strings

See how Wikidata can help table [Table_of_administrative_divisions_by_country ](https://en.wikipedia.org/wiki/Table_of_administrative_divisions_by_country)

* [Introduction to Wikidata](https://www.youtube.com/watch?v=m_9_23jXPoE)

I think it will be much easier if we have not just text strings but same as Wikidata

We changed the country reporting to using [ISO 3 lettercode](https://twitter.com/redouad/status/1343979726667395073?s=20)

![image](https://user-images.githubusercontent.com/14206509/104838963-70892a00-58be-11eb-80a0-42a2471d2562.png)

![image](https://user-images.githubusercontent.com/14206509/104838965-767f0b00-58be-11eb-903b-68f7b6030def.png)

**Comment by lucasrodes** [comment]
Hi @salgo60 and thanks for your comment.

If I understand it right, you propose to add a column with ISO 3166-1 codes for countries (https://en.wikipedia.org/wiki/ISO_3166-1)?

I have seen that there is also [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) for principal subdivisions of countries.

We can perhaps add both to the datasets

**Comment by lucasrodes** [comment]
I have updated the files, now ISO codes for location (country) and region (subnational) are available.

[data](https://github.com/lucasrodes/covid19-vaccination-subnational/blob/main/data/vaccinations.csv).

I'll close this issue, but feel free to re-open it (or create a new one).

Thanks for your feedback 😄 !

**Comment by salgo60** [comment]
Cool then you can use Wikidata and display the numbers on a [map](https://w.wiki/ui$) or in different languages [en](https://w.wiki/uj4), [ar](https://w.wiki/uj6), [zh](https://w.wiki/uj8)

![image](https://user-images.githubusercontent.com/14206509/104877015-2903ac00-5959-11eb-8fd9-cbf2fdfa0b01.png)
