### ISSUE TITLE
Make changes to data scraper for India

### ISSUE THREAD

**Issue by sanyam-git** [sociepy/covid19-vaccination-subnational#30]
I have made the changes as mentioned [here](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/issues/3). You can make the changes to the project w.r.t this.

I have made both [state_timeline.json](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/blob/main/api/state_timeline.json) and [state_timeline.csv](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/blob/main/csv/state_timeline.csv) as per the new structure, you can use whatever best suits.

**Comment by lucasrodes** [comment]
Great!
Thanks, @sanyam-git, will add this today!

**Comment by lucasrodes** [comment]
I finally chose to use the [csv](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/blob/main/csv/state_timeline.csv) file format.

Closing this, feel free to reopen
