### ISSUE TITLE
Add sweden data

### ISSUE THREAD

**Issue by lucasrodes** [sociepy/covid19-vaccination-subnational#4]
Sweden can be easily added, regional data is available [here](https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/vaccination-mot-covid-19/statistik-over-forbrukade-vaccindoser/).

OWID uses this source, [their script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/incremental/sweden.py) with the corresponding attribution could be used.

**Comment by salgo60** [comment]
@lucasrodes  Sweden is moving around its data ;-(
