### ISSUE TITLE
NaN returns invalid JSON

### ISSUE THREAD

**Issue by SamuelGHill** [sociepy/covid19-vaccination-subnational#40]
I am building out a GraphQL Server with [StepZen](https://stepzen.com/) and the query `https://sociepy.org/covid19-vaccination-subnational/data/api/v1/latest/country_by_iso/FR.json` breaks due to a NaN value rather than null value in total_vaccinations_per_100.  

// Response from RestAPI

```
        {
            "region_name": "Corse",
            "region_iso": "FR-COR",
            "date": "2021-02-22",
            "total_vaccinations": 27059,
            "total_vaccinations_per_100": NaN
        },
```

GraphQL Query
```
  vaccines(countryISO: "FR") {
  country
  }
```

Response Error
```
{
  "data": {
    "vaccines": null
  },
  "errors": [
    {
      "message": "Invalid json content.: invalid character 'N' looking for beginning of value",
      "locations": [
        {
          "line": 58,
          "column": 3
        }
      ],
      "path": [
        "vaccines"
      ]
    }
  ]
}
```

**Comment by lucasrodes** [comment]
Hi @SamuelGHill,
Thanks for your report! Also, happy to see that you find this project useful.

I will start working on this asap, I'll ping you when fixed.

**Comment by lucasrodes** [comment]
@SamuelGHill 
Could you check now? Thanks!

Also, I'd be happy to learn more about your project 😄

**Comment by SamuelGHill** [comment]
@lucasrodes 

Works! Thank you for the quick fix. 

And yes, I'd be more than happy to.  I'll share my project with you and see what collaborations we can do!
