### ISSUE TITLE
Data not updating for India

### ISSUE THREAD

**Issue by sanyam-git** [sociepy/covid19-vaccination-subnational#56]
Hi @lucasrodes, the data for India is not updating after 20/4/2021.
However the data at the source is til 22/4/2021 -> [state_timeline.csv](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/blob/main/csv/state_timeline.csv)

**Comment by lucasrodes** [comment]
Thanks for reporting @sanyam-git!
Apparently, the pipeline for Spain & Sweden was not working and let the script not run until the end.

FYI, you can check this here:
- Go the [actions](https://github.com/sociepy/covid19-vaccination-subnational/actions/) section.
- Click on last run (named `refresh`)
- Click on  the build
- Go to step "Data refresh"

[link here](https://github.com/sociepy/covid19-vaccination-subnational/runs/2425498862?check_suite_focus=true)

Screenshot below:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/18101289/115956784-bde8e900-a4f6-11eb-9c41-dd3b24943ded.png">

**Comment by sanyam-git** [comment]
@lucasrodes , Thanks for the explanation regarding actions logs. I'm quite not yet familiar with GitHub Actions,  so it is helpful.

You are doing great work lately, keep it up !

Also just a suggestion, can you put a try-except statement so if one country update gives error, it will not affect the countries after that.

**Comment by lucasrodes** [comment]
Thanks for your words @sanyam-git . I should definitely add try-catch logic, good point. Ill try to do it soon.

Have a good day!
