### ISSUE TITLE
Heads-up: structure of upstream data for Germany changed

### ISSUE THREAD

**Issue by mathiasbynens** [sociepy/covid19-vaccination-subnational#63]
Due to upstream changes, we had to change our data structure a bit: https://github.com/mathiasbynens/covid-19-vaccinations-germany/blob/main/data/data.csv

- All columns with the `first` prefix have been renamed to `initial`, e.g. `firstDosesCumulative` → `initialDosesCumulative`.
- All columns with the `second` prefix have been renamed to `final`, e.g. `secondDosesCumulative` → `finalDosesCumulative`
- New columns are added for J&J vaccinations (but I think this part doesn’t affect your project).

**Comment by lucasrodes** [comment]
Hi, 
Thanks for the heads up on Germany data!

Quick question, a J&J administered dose would increment both fields `initialDosesCumulative` and `finalDosesCumulative`?

If so, I may have to change the current computation of total vaccinations administered.

**Comment by mathiasbynens** [comment]
No, a final dose is never an initial dose. J&J doses only count towards `finalDosesCumulative`, matching the source sheet. I'll add a FAQ entry to the README to clarify this.

**Comment by mathiasbynens** [comment]
Clarified it here: https://github.com/mathiasbynens/covid-19-vaccinations-germany/blob/main/README.md#initialdoses-vs-finaldoses

I'm open to suggestions for better names. I had considered `partialDoses` instead of `initialDoses` but that sounds like half a dose is administered :| Another one that came to mind is `nonFinalDoses` which has the benefit of being unambiguous, but... it sounds a bit weird.

**Comment by lucasrodes** [comment]
Thanks for the clarification, @mathiasbynens.

I find your choice quite smart and simple. This way the total number of doses administered can still be obtained by means of simple addition (`initialDosesCumulative`+`finalDosesCumulative`).

Thanks for adding the section in the README, appreciate it.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/covid-19-vaccinations-germany#partially-vs-fully-vaccinated
