### ISSUE TITLE
Data for Ukraine 🇺🇦

### ISSUE THREAD

**Issue by denysdovhan** [sociepy/covid19-vaccination-subnational#69]
Thanks for making that project!

There's an official live dashboard for the Ukrainian vaccination process: https://health-security.rnbo.gov.ua/vaccination

It uses data from an open API endpoint: https://health-security.rnbo.gov.ua/api/vaccination/process/map?distributionBy=vaccine&vaccines=&dose=1&date=2021-04-27

I'd gladly help writing a scrapper by myself, but I'm not particularly strong in Python. Nevertheless, I can help by answering possible questions.

I'll ask some folks on Twitter for help with writing a scrapper for that API.

**Comment by lucasrodes** [comment]
Hi @denysdovhan!
Thanks for reporting this. Let me know if you start working on this, otherwise, I may start whenever I have some time left!

**Comment by lucasrodes** [comment]
Thanks once again for your report.

I have added Ukraine in 308ef45 

You can now see details on last update in the [README.md](https://github.com/sociepy/covid19-vaccination-subnational/README.md). Also, available via static API: https://sociepy.org/covid19-vaccination-subnational/data/api/v1/.

Feel free to inspect the script importing the data [here](https://github.com/sociepy/covid19-vaccination-subnational/blob/main/src/covid_updater/scraping/countries/ukraine.py)
